### GET actor index
GET http://localhost:3000/actors

### GET actor show
GET http://localhost:3000/actors/5

### POST actor create
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Jet",
  "last_name": "Li",
  "known_for": "The One"
}

### PATCH actor update
PATCH http://localhost:3000/actors/7
Content-Type: application/json

{
  "known_for": "The Fifth Element"
}

### DELETE actor destroy
DELETE http://localhost:3000/actors/8

### GET movie index
GET http://localhost:3000/movies

### GET movie show
GET http://localhost:3000/movies/5

### POST movie create
POST http://localhost:3000/movies
Content-Type: application/json

{
 "title": "Stuff and stuff",
 "year": 2022,
 "plot": "its about stuff and stuff"
}

### PATCH movie update
PATCH http://localhost:3000/movies/7
Content-Type: application/json

{
  "title": "More stuff and stuff"
}

### DELETE movie destroy
DELETE http://localhost:3000/movies/7