### GET actor index
GET http://localhost:3000/actors

### GET actor show
GET http://localhost:3000/actors/5

### POST actor create
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Emma",
  "last_name": "Stone",
  "known_for": "Easy A",
  "gender": "female",
  "age": 30,
  "movie_id": 11
}

### PATCH actor update
PATCH http://localhost:3000/actors/9.json
Content-Type: application/json

{
  "movie_id": 10
}

### DELETE actor destroy
DELETE http://localhost:3000/actors/8

### GET movie index
GET http://localhost:3000/movies

### GET movie show
GET http://localhost:3000/movies/5

### POST movie create
POST http://localhost:3000/movies
Content-Type: application/json

{
 "plot": "one"
}

### PATCH movie update
PATCH http://localhost:3000/movies/4
Content-Type: application/json

{
  "plot": "c"
}

### DELETE movie destroy
DELETE http://localhost:3000/movies/7

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name 3",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}