### GET actor index
GET http://localhost:3000/actors

### GET actor show
GET http://localhost:3000/actors/5

### POST actor create
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "J",
  "last_name": "L",
  "age": 11
}

### PATCH actor update
PATCH http://localhost:3000/actors/5
Content-Type: application/json

{
  "age": 9
}

### DELETE actor destroy
DELETE http://localhost:3000/actors/8

### GET movie index
GET http://localhost:3000/movies

### GET movie show
GET http://localhost:3000/movies/5

### POST movie create
POST http://localhost:3000/movies
Content-Type: application/json

{
 "plot": "one"
}

### PATCH movie update
PATCH http://localhost:3000/movies/4
Content-Type: application/json

{
  "plot": "c"
}

### DELETE movie destroy
DELETE http://localhost:3000/movies/7